### ISSUE TITLE
Question to recursive components?

### ISSUE THREAD

**Issue by vilinski** [astynax/tea-combine#1]
Hi, seen your presentation about elm, cool utility. Just one question.
I'm new to elm. You have an example for a list of elements. Is it also possible with your lib (or current elm at all) to compose recursive elements?
I am looking for a general solution for a `TreeView CheckBox` or `Accordion Counter` alike structure with nested view elements, each with own view, update, msg etc.

**Comment by astynax** [comment]
Hello.
Element nesting in Elm is pretty straightforward:
```elm
module Main exposing (main)

import Array exposing (Array)
import Browser
import Html exposing (..)
import Html.Events exposing (onClick)
import List
import Maybe


type Node
    = Node Int (Array Node)


init =
    Node 0 <|
        Array.fromList
            [ Node 1 Array.empty
            , Node 2 <|
                Array.fromList
                    [ Node 3 Array.empty
                    ]
            ]


type Msg
    = At Int Msg
    | Inc


main =
    Browser.sandbox
        { init = init
        , view = view
        , update = update
        }


view (Node val nodes) =
    div []
        [ text <| Debug.toString val
        , button [ onClick Inc ] [ text "+" ]
        , button [ 
        , ul [] <|
            List.indexedMap
                (\i x ->
                    li []
                        [ Html.map (At i) <| view x
                        ]
                )
            <|
                Array.toList nodes
        ]


update msg (Node val nodes) =
    case msg of
        Inc ->
            Node (val + 1) nodes

        At idx m ->
            let
                node =
                    update m <|
                        Maybe.withDefault (Node 0 Array.empty) <|
                            Array.get idx <|
                                nodes
            in
            Node val <| Array.set idx node nodes
```
(you can try this code with http://elm-lang.org/try)

Here all the nodes have same model, view and update, but you can compose a non-heterogenic lists of elements in the same way. A common pattern here is to wrap child's submessages to some auxiliary message, which also will keep an index of child model within a parent model.

**Comment by vilinski** [comment]
Thank you for explanation and example! I think now I have a grasp

**Comment by astynax** [comment]
Thank you for good question!
