### ISSUE TITLE
Add a good explanational tutorial, at least for the simple stuff like the Both+Either composition.

### ISSUE THREAD

**Issue by supermacro** [astynax/tea-combine#6]
Can someone provide a simple explanation of how this all works as someone who hasn't really worked with combinators in the past? Looking at the example it looks like black magic (which I very much would like to attain & grasp).

**Comment by Maldus512** [comment]
Say you have an arbitrary number of components, each one with its `Model` and `Msg` types, plus the `update` and `view` functions.

This library handles an automatic combination of said components. Intuitively, it just smashes together models and messages in "master" types that are then communicated to The Elm Architecture beneath.
The combination itself is really simple: the combined `Model` type just becomes a tuple of all the subcomponent's `Model`s. If you take a look at the `initWith` function you can see this simple combination:

https://github.com/astynax/tea-combine/blob/9eca5a62f8787abe452e8c488783db9706687b11/src/TeaCombine/Pure/Pair.elm#L19-L24

It simply takes two models and returns a tuple of them. Then it's clear what happens in the example in the README: writing

```elm
Counter.init 0
                |> initWith (CheckBox.init False)
                |> initWith (CheckBox.init False)
```

Results in a tuple `((m1, m2), m3)` where `m1` is the model of the counter, `m2` is the model of the first checkbox and `m3` of the second. This is the automagic combination of the `Model` type.

The `Msg` type is combined with `Either` (https://package.elm-lang.org/packages/toastal/either/latest/Either), which corresponds to the sum of the specified type: each component specifies its messages, `msg1`, `msg2` and `msg3`. The top `Msg` type which is given to the `sandbox` is an `Either (Either msg1 msg2) msg3`, though the combination made by `updateWith` is a little more complex. In the example, counters have `Int` as their messages, while a checkbox has `()`. The final result will be something that is either an `Int`, a `()` for the first checkbox or a `()` for the second checkbox.

In the end the "master" `update` function that is created will take something that is either `msg1`, `msg2` or `msg3`,  automagically route it to the correct sub`update` function and it will return a tuple `((m1, m2), m3)`.

This combination can be done by hand, but I bet you can see that automatically doing so is more sane.
I hope I made the library a little clearer to you!

**Comment by astynax** [comment]
@Maldus512 it was awesome! Can I ask you to make a real tutorial or transform this text into comments for the one of examples?

**Comment by Maldus512** [comment]
Thanks! I'll try to make it a more complete tutorial this weekend

**Comment by Maldus512** [comment]
@astynax I've wrote a more complete explanation as a Medium article: https://medium.com/@mattia512maldini/the-principles-behind-tea-combine-49120b9137d0.
Is this what you meant?  If it's ok for you I'll give it a final review and publish it. Check out especially the last part where I draw conclusions and list some downsides; I'm interested in knowing if you think that these are fair assesments.

**Comment by astynax** [comment]
@astynax wow! Awesome work!

Can you just add a small bit about the `Many` related stuff? Just as a small note maybe. This kind of composition is really helpful when you have a long but *heterogeneous* set of components, then this family of combinators will compose a single array model instead of the nested single-linked list of pairs.

**Comment by Maldus512** [comment]
I added just a brief paragraph about `Many`; I don't want to overload it too much, it's already a very lengthy explanation

**Comment by astynax** [comment]
@Maldus512 looks great, many thanks to you!

**Comment by astynax** [comment]
@Maldus512 is there any chance to know when you will finish your tutorial? I really want to mention it in the README :)

**Comment by Maldus512** [comment]
Whoops, I published but failed to mention it here.
Here it is: https://medium.com/@mattia512maldini/the-principles-behind-tea-combine-49120b9137d0

**Comment by astynax** [comment]
@Maldus512 thank you! One last wish: can you [move](https://help.medium.com/hc/en-us/articles/360018637634-Remove-post-from-the-paywall) the Medium post outside the paywall, please? It will be sad if half of the potential readers won't be able (without some tricks) to read your article because of Medium's greediness...

**Comment by Maldus512** [comment]
Done (I think?)! It's embarassing, I thought it was on the free list already.
It's been a while since I've published on Medium and I couldn't find the option any more. I checked the link without logging in into my account and I could still see it... Can you confirm it's out of the paywall now?

**Comment by astynax** [comment]
@Maldus512 yay, now it's free! Thanks a lot!

**Comment by astynax** [comment]
Just added a link to the tutorial in README.
